apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: conveyor-etl-system

resources:
  - operator/namespace.yaml
  - operator/serviceaccount.yaml
  - operator/rbac.yaml
  - operator/deployment.yaml
  - crds/crds.yaml

images:
  - name: conveyor-etl-operator
    newTag: latest
