apiVersion: conveyor.router/v1
kind: Sink
metadata:
  name: grpc-analytics
  namespace: default
spec:
  grpc:
    endpoint: analytics-svc:50051
    proto: etl.sink.SinkService
  config:
    timeout_ms: 5000
