apiVersion: v1
kind: ServiceAccount
metadata:
  name: conveyor-etl-operator
  namespace: conveyor-etl-system
  labels:
    app.kubernetes.io/name: conveyor-etl-operator
    app.kubernetes.io/component: operator
