apiVersion: v2
name: conveyor-etl-operator
description: Kubernetes operator for Conveyor ETL clusters
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - etl
  - data-pipeline
  - kubernetes-operator
  - raft
maintainers:
  - name: Conveyor ETL Team
